initial wip push for steve to look
uktrade/great-cms pull request #1100
Opened 2021-03-25 12:42 UTC by Rambowalsh

### Workflow

- [x ] Ticket exists in Jira https://uktrade.atlassian.net/browse/GP2-1648
- [ x] Jira ticket has the correct status.
- [x ] [Changelog](CHANGELOG.md) entry added.

### Merging

- [x] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

2021-03-25 14:19 UTC, stevejalim commented on config/settings.py
> +
Would be good to move these to the top of the file, by `ROOT_DIR`

2021-03-25 14:19 UTC, stevejalim commented on core/management/commands/download_geolocation_data.py
> +        geolocation_archive.decompress(file_name=settings.GEOIP_COUNTRY, destination=settings.GEOIP_PATH)
Looks like we might need an additional line for settings.GEOIP_CITY too
`geolocation_archive.decompress(file_name=settings.GEOIP_CITY, destination=settings.GEOIP_PATH)`

2021-03-25 14:19 UTC, stevejalim commented on tests/unit/core/management/commands/test_download_geolocation_data.py
> +    )
I think we'll also need to expand these tests to cover the GEOIP_CITY database, too

2021-03-29 08:25 UTC, Rambowalsh commented on tests/unit/core/management/commands/test_download_geolocation_data.py
> +    )
Added GeoCity tz file and amrended test_handles_remote_invalid_archive
to run against this new city compressed file

2021-03-29 16:04 UTC, stevejalim commented on core/management/commands/download_geolocation_data.py
> +        geolocation_archive.decompress(file_name=settings.GEOIP_COUNTRY, destination=settings.GEOIP_PATH)
@Rambowalsh  Ah, yeah - looking at existing code in export-plan we still need the GEOIP_CITY stuff to be loaded, so we're gonna have to back-out some of these changes the downloader to make sure we get the country stuff _and_ the city stuff.

2021-03-29 16:06 UTC, stevejalim requested changes
heya @Rambowalsh - thanks for this. Looking now more at the surrounding code, I think we need to back out some of the changes to the downloader so that we DO get both the Country and the City data. At the moment it reads like we only now update the country file (which is what i saw when i pulled new data locally, too).

Sorry to bounce this back, but if you could slightly rewind the tests (even by hand, looking at the diff here) that'd be great and would unblock this. Cheers!

2021-03-29 16:09 UTC, stevejalim commented
@Rambowalsh Let's check in with each other before you pick this back up, as it might alternatively be better to drop the CITY use and go only with COUNTRY. Will see what I can find out in the meantime

2021-03-29 17:22 UTC, Rambowalsh commented
Ok

On Mon, 29 Mar 2021, 17:09 Steve Jalim, ***@***.***> wrote:

> @Rambowalsh <https://github.com/Rambowalsh> Let's check in with each
> other before you pick this back up, as it might alternatively be better to
> drop the CITY use and go only with COUNTRY. Will see what I can find out in
> the meantime
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/uktrade/great-cms/pull/1100#issuecomment-809511079>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOVQZQ34KWX7IHY77LV5N2LTGCX4BANCNFSM4ZZI6MQQ>
> .
>

2021-03-29 20:48 UTC, stevejalim commented
@Rambowalsh Yeah, looking around I can see that `core.helpers.get_location()` is used in a couple of places and this `get_location()` function uses the City database, too. So, unfortunately, we'll have to back in the code and tests that load the  city data as well. I think basically anywhere we're loading/fetching/updating the GeoIP Country data we should be doing the same for the City data. Apols for not noticing that earlier in things, but I don't think it's lot of work to add in.

2021-03-31 15:50 UTC, stevejalim reviewed
Given this a look over and it seems fine - but I'd rather someone else review it as I've been quite close to the code

2021-03-31 15:50 UTC, stevejalim commented on README.md
> +This project includes GeoLite2 data created by MaxMind, available from https://www.maxmind.com/
This was added to comply with the CC attribution requirement noted on https://dev.maxmind.com/geoip/geoip2/geolite2/ @agiamas

2021-03-31 16:03 UTC, webbyfox approved these changes
LGTM

2021-03-31 16:11 UTC, merged