GP2-2944 DAC_Reflow_01
uktrade/great-cms pull request #1409
Opened 2021-06-17 18:24 UTC by seijihg

Page 140 of the DAC Report May.

Fixed overflow with high zoom.

After:
<img width="1246" alt="Screenshot 2021-06-17 at 19 12 50" src="https://user-images.githubusercontent.com/24960282/122452449-2c02d700-cfa1-11eb-8a98-1b72b55c94a7.png">

### Workflow

- [x] Ticket exists in Jira https://uktrade.atlassian.net/browse/GP-2944
- [x] Jira ticket has the correct status.
- [x] [Changelog](CHANGELOG.md) entry added.

### Reviewing help

- [ ] Explains how to test locally, including how to set up appropriate data
- [x] Includes screenshot(s) - ideally before and after, but at least after

### Housekeeping

- [ ] Added all new environment variables to Vault.
- [ ] Cleaned up old feature flags
- [ ] Upgraded any vulnerable dependencies.
- [ ] Ran the `make manage download_geolocation_data` command
- [ ] I have updated security dependencies
- [ ] Python requirements have been re-compiled.
- [ ] Frontend assets have been re-compiled.

### Merging

- [x] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

2021-06-18 15:13 UTC, bobmeredith commented on core/sass/components/_modal-cms.scss
>  .ReactModal__Body--open {
As you've changed an scss file, there should be a compiled .css and a .map with it.  Perhaps also a package.lock.
Run `npm run build` to generate these.  Same goes for changes to JavaScript .js or .jsx

2021-06-18 15:14 UTC, bobmeredith commented on CHANGELOG.md
> +
As with other files, would be good to revert this reformat of changelog.

2021-06-18 15:15 UTC, bobmeredith requested changes
scss needs compiling and there is a reformat of changelog.

2021-06-22 07:46 UTC, bobmeredith approved these changes
I'm not sure why there is a built .js file in here as there are no .js changes so your built js should match exactly the one in GH.
Anyway, you need to rebase off develop, then 'npm build' before you can merge.
in theory, the .js update should go away.
BTW, check that you turn off any 'npm watch' before building as it will overwrite the static resources with dev ones.

2021-06-22 07:51 UTC, bobmeredith commented
Something has clearly gone wrong with your pull/merge/build process as there are real code changes in the JS file.
![image](https://user-images.githubusercontent.com/11422209/122885444-ff4f1680-d336-11eb-83d8-04653d7b7b1e.png)

2021-06-22 16:25 UTC, seijihg commented
> I'm not sure why there is a built .js file in here as there are no .js changes so your built js should match exactly the one in GH.
> Anyway, you need to rebase off develop, then 'npm build' before you can merge.
> in theory, the .js update should go away.
> BTW, check that you turn off any 'npm watch' before building as it will overwrite the static resources with dev ones.

Lemme try rebase and see I had watch on when rebuilding so that might caused the problem.

2021-06-22 17:07 UTC, merged