GP2-2936 Dac Custom Controls 04
uktrade/great-cms pull request #1413
Opened 2021-06-21 08:28 UTC by seijihg

- Added Aria and role for <div> radiogrpitem for JAWS recognition. Tested with ChromeVox on Mac

Should recognise when radio is disabled or enabled.

npm run build

### Workflow

- [x] Ticket exists in Jira https://uktrade.atlassian.net/browse/GP2-2936
- [x] Jira ticket has the correct status.
- [x] [Changelog](CHANGELOG.md) entry added.

### Reviewing help

- [ ] Explains how to test locally, including how to set up appropriate data
- [ ] Includes screenshot(s) - ideally before and after, but at least after

### Housekeeping

- [ ] Added all new environment variables to Vault.
- [ ] Cleaned up old feature flags
- [ ] Upgraded any vulnerable dependencies.
- [ ] Ran the `make manage download_geolocation_data` command
- [ ] I have updated security dependencies
- [ ] Python requirements have been re-compiled.
- [x] Frontend assets have been re-compiled.

### Merging

- [x] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

2021-06-21 12:13 UTC, bobmeredith commented on react-components/src/components/Form/Radiogroup/RadiogroupItem.jsx
> +import React, { memo, useState, useEffect } from 'react'
Looks like useState and useEffect are not being used.  I guess eslint will moan about this.

2021-06-21 12:14 UTC, bobmeredith requested changes
Need to remove unused imports.

2021-06-22 16:42 UTC, seijihg commented on react-components/src/components/Form/Radiogroup/RadiogroupItem.jsx
> +import React, { memo, useState, useEffect } from 'react'
fixed thanks for pointing this!

2021-06-23 08:23 UTC, bobmeredith approved these changes
LGTM

2021-06-23 08:23 UTC, merged