Gp2-3102: Vulnerable JS packages in great-cms/domestic/\* need updating
uktrade/great-cms pull request #1460
Opened 2021-07-19 18:11 UTC by seijihg

Updated packages and gulpfile.js in both core/components and domestic. Updated commands to make it more streamlined in both places. Everything is updated in the README.md

### Workflow

- [x] Ticket exists in Jira https://uktrade.atlassian.net/browse/GP2-3102
- [x] Jira ticket has the correct status.
- [x] [Changelog](CHANGELOG.md) entry added.

### Reviewing help

- [ ] Explains how to test locally, including how to set up appropriate data
- [ ] Includes screenshot(s) - ideally before and after, but at least after

### Housekeeping

- [ ] Added all new environment variables to Vault.
- [ ] Cleaned up old feature flags
- [ ] Upgraded any vulnerable dependencies.
- [ ] Ran the `make manage download_geolocation_data` command
- [ ] I have updated security dependencies
- [ ] Python requirements have been re-compiled.
- [ ] Frontend assets have been re-compiled.

### Merging

- [x] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

2021-07-19 19:43 UTC, stevejalim reviewed
LGTM - got a comment about a file that maybe shouldn't have changed / maybe changes back if you re-run the command.

Also, lots of deprecated package warnings, but it DOES work, which is good :)

Hopefully none of the new packages will have theirown vulns!

2021-07-19 19:43 UTC, stevejalim commented on core/components/static/stylesheets/elements-components.css
> +  background-color: blue; }
When i run gulp build in core/components, this change is removed

```
-  background: #ffffff;
-  background-color: blue; }
+  background: #ffffff; }
```

Maybe worth re-running gulp build on this branch and seeing if it disappears for you, too? If so, check in the 'reverted' file, I think...

2021-07-19 19:43 UTC, stevejalim commented
Important postscript: NICE WORK. Thank you! 🙌

2021-07-20 08:16 UTC, bobmeredith commented on core/components/gulpfile.js.bak
> +'use strict'
I guess this is a copy of the old gulpfile.  Could you delete please.

2021-07-20 08:17 UTC, bobmeredith commented on core/components/overrides/govuk_elements/elements/_layout.scss
>    width: 100%;
Nothing but reformatting in this file. Would you revert it please

2021-07-20 08:19 UTC, bobmeredith commented on core/components/react-components/webpack.config.js
> -const path = require('path');
Looks like your tab width is different.  I guess there are no real changes to this file.  If not, please revert.

2021-07-20 08:21 UTC, bobmeredith commented on core/components/sass/components/utils/_base.scss
> -  ($black, black),
Surely this looks wrong. These are sass variable declarations - they should start with '$'

2021-07-20 08:28 UTC, bobmeredith commented on core/components/sass/components/accordion/_base.scss
>    details.great-accordion:last-child {
This is just reformatting right? If so, best to revert.

2021-07-20 11:20 UTC, bobmeredith commented on core/components/sass/components/accordion/_base.scss
> -details.great-accordion[closed] summary:before,
This looks like a functional change right? the comma is lost.

2021-07-20 11:20 UTC, bobmeredith commented on core/components/static/stylesheets/elements-components.css
> +details.great-accordion[closed] summary:before details.great-accordion[open] summary:before {
... and the change above is reflected in css here.

2021-07-20 11:22 UTC, bobmeredith commented on core/components/static/stylesheets/elements-components.css
> -  width: 100%;
This is a real .css difference

2021-07-20 11:22 UTC, bobmeredith commented on core/components/static/stylesheets/elements-components.css
> -      margin: 12px 0 10px 10px;
This is a real .css difference

2021-07-20 11:27 UTC, bobmeredith requested changes
Hmm, In a perfect world, I would not expect the compiled .css to change at all, and yet I see a hodload of differences.  Some of them look functional and I don't see corresponding scss changes so I'm thinking something must be wrong. Also there are functional scss changes too - and there shouldn't be any of those.
Make sure it's clean and revert all scss file changes. Then build with the new scripts and you should see identical css and minified css I think. If that's the case, brilliant; if not, you'll need to work out if the changes are significant or not.

2021-07-21 09:11 UTC, stevejalim commented on core/components/static/stylesheets/elements-components.css
> -@font-face {
@seijihg Sorry, but how come this large amount of styling is disappearing? Are we sure it's safe to remove?

2021-07-30 12:44 UTC, bobmeredith approved these changes

2021-07-30 12:45 UTC, merged