Adding govuk frontend npm package, include in IOO
uktrade/great-cms pull request #1994
Opened 2023-02-13 08:36 UTC by stuart-madetech

(Please add a sentence or two explaining the context of this PR. Reviewers can go to the ticket for detail.)
CONTEXT: This changeset adds/removes/updates [summary of feature/area/code] so that [summary of benefit].

_Tick or delete as appropriate:_

### Workflow

- [ ] Ticket exists in Jira https://uktrade.atlassian.net/browse/ioo-400
- [ ] Jira ticket has the correct status.
- [ ] [Changelog](CHANGELOG.md) entry added.

### Reviewing help

- [ ] Includes screenshot(s) - ideally before and after, but at least after

### Housekeeping

- [ ] Ran the `make manage download_geolocation_data` command
- [ ] Python requirements have been re-compiled.
- [ ] Frontend assets have been re-compiled.

### Merging

- [x] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

2023-02-13 10:52 UTC, mforner13 requested changes
I see you've brought in the gov uk style kit as an npm package. It looks like we've already got the main css file [here](https://github.com/uktrade/great-cms/blob/develop/core/components/static/stylesheets/govuk-elements-styles.css). I think it's best to not duplicate it, so it might be worth trying to remove that css file and see if just the npm package can be used?

2023-02-13 10:52 UTC, mforner13 commented on international_online_offer/templates/ioo/includes/phase_banner.html
> +        </span>
Do we know where the feedback link will lead to?

2023-02-13 10:52 UTC, mforner13 commented on international_online_offer/templates/ioo/index.html
> +            </p>
Should the 'terms and conditions' text be a link to our terms and conditions page?

2023-02-14 15:12 UTC, stuart-madetech commented on international_online_offer/templates/ioo/index.html
> +            </p>
Done

2023-02-14 15:48 UTC, mforner13 commented on CHANGELOG.md
> +* IOO-400 - International Online Offer adding govuk frontend toolkit and using in index
Might be worth updating this now we're not adding the whole toolkit :)

2023-02-14 15:52 UTC, mforner13 commented on international_online_offer/sass/_inset-text.scss
> +  // @include govuk-responsive-margin(6, "bottom");
Should these be uncommented? :)

2023-02-15 09:43 UTC, stuart-madetech commented on international_online_offer/sass/_inset-text.scss
> +  // @include govuk-responsive-margin(6, "bottom");
Done :)

2023-02-15 09:45 UTC, mforner13 approved these changes
👍

2023-02-15 10:06 UTC, merged