International online offer triage question one
uktrade/great-cms pull request #2001
Opened 2023-02-17 10:56 UTC by stuart-madetech

Initial page allowing investors to select their sector as part of a 5 step triage. 

### Workflow

- [ ] Ticket exists in Jira https://uktrade.atlassian.net/browse/IOO-402
- [ ] Jira ticket has the correct status.
- [ ] [Changelog](CHANGELOG.md) entry added.

### Reviewing help

- [ ] Explains how to test locally, including how to set up appropriate data
- [ ] Includes screenshot(s) - ideally before and after, but at least after

Before:
N/A
After:
[Screenshot 2023-02-15 at 14 16 16](https://user-images.githubusercontent.com/75611506/219627763-ac861f74-a1f8-4bab-ab86-291d93730593.png)

### Housekeeping

- [ ] Python requirements have been re-compiled.
- [ ] Frontend assets have been re-compiled.

### Merging

- [x] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

2023-02-20 12:06 UTC, mforner13 requested changes
Looks good, just a few fairly small changes needed :)

2023-02-20 12:06 UTC, mforner13 commented on international_online_offer/views.py
> +class IOOSector(TemplateView):
Just need to add a test for this view :) Same pattern you used for the [index view test](https://github.com/uktrade/great-cms/blob/develop/tests/unit/international_online_offer/test_views.py)

2023-02-20 12:06 UTC, mforner13 commented on international_online_offer/templates/ioo/triage/sector.html
> +                  We’ll use these information to provide customised content relevant to your sector and products or services.
Should the text be 'use **this** information'?

2023-02-20 13:47 UTC, stuart-madetech commented on core/static/javascript/ioo-sector.js
> +    suggestion: suggestionTemplate
I think thats by design. If you hit tab it autocompletes to the hint shown. Happy to remove it if you think otherwise? :)

2023-02-20 14:02 UTC, mforner13 commented on core/static/javascript/ioo-sector.js
> +    suggestion: suggestionTemplate
I think would be fine if the text perfectly overlayed but with the current setup the user's text is slightly below the hint text on mobile and to the right on desktop. Perhaps the text size or spacing is v slightly different between the two? :) 

But up to you as to whether you want to fix or remove :)

2023-02-23 10:28 UTC, mforner13 commented on international_online_offer/forms.py
> +        ('', ''),
Is this option needed? :)

2023-02-23 10:28 UTC, mforner13 commented on international_online_offer/templates/ioo/triage/sector.html
> +        { "Food & Drink": ["casual dining","dining","alcoholic drinks","bakery products","brewing","dairy products","food and drink manufacturing","free from","allergen free food","frozen and chilled
I don't think it feels right storing these values in the template - passing through via context on the view would be the more standard django pattern I think :) 

[Example here](https://github.com/uktrade/great-cms/blob/develop/core/views.py#L63)

2023-02-23 10:28 UTC, mforner13 commented on international_online_offer/templates/ioo/triage/sector.html
> +    }
In the next PR it would be good to make these reusable functions in a central IOO js file, as I'm guessing you'll be following this pattern for all forms in the triage flow :)

2023-02-23 10:28 UTC, mforner13 commented on CHANGELOG.md
> +* IOO-402 - International Online Offer triage question 1 allowing user to select business sector
Looks like these entries are accidentally in the 2.25.0 release. Once you've rebased from develop, can move them into the appropriate sections :)

2023-02-23 10:32 UTC, stuart-madetech commented on core/static/javascript/ioo-sector.js
> +function customSuggest (query, syncResults) {
File is now deleted

2023-02-23 10:37 UTC, stuart-madetech commented on core/static/javascript/ioo-sector.js
> +    suggestion: suggestionTemplate
Have removed it :)

2023-02-23 10:37 UTC, stuart-madetech commented on international_online_offer/views.py
> +class IOOSector(TemplateView):
Added test

2023-02-23 10:39 UTC, stuart-madetech commented on international_online_offer/templates/ioo/triage/sector.html
> +    }
Agreed completely. Ill strip them out when used elsewhere

2023-02-23 10:42 UTC, stuart-madetech commented on international_online_offer/forms.py
> +        ('', ''),
Unfortunately yes, design has no "Please select" etc as the top entry in the select and without it defaults to the top option eg. 'Aerospace'

2023-02-23 10:44 UTC, mforner13 commented on international_online_offer/forms.py
> +        ('', ''),
Ahh makes sense! A comment here explaining it would be useful I think :)

2023-02-23 11:04 UTC, stuart-madetech commented on international_online_offer/templates/ioo/triage/sector.html
> +        { "Food & Drink": ["casual dining","dining","alcoholic drinks","bakery products","brewing","dairy products","food and drink manufacturing","free from","allergen free food","frozen and chilled
Happy to do this - we have another dev task down the time to do this properly. Ideally I'll be getting a json file that can be read in and added to a const and then pass down via context but the shape of the file is changing often. Didn't want to put effort into this if it's going to change.

2023-02-23 11:24 UTC, rafa-garcia commented on international_online_offer/templates/ioo/triage/sector.html
> +        { "Food & Drink": ["casual dining","dining","alcoholic drinks","bakery products","brewing","dairy products","food and drink manufacturing","free from","allergen free food","frozen and chilled
@stuart-madetech there is one JSON fixture for sectors [here](https://github.com/uktrade/directory-constants/blob/9f72eb0fad25f8b521a59886a9bcc903111b4387/directory_constants/fixtures/dit-sector-list.json)

2023-02-23 11:30 UTC, stuart-madetech commented on international_online_offer/templates/ioo/triage/sector.html
> +        { "Food & Drink": ["casual dining","dining","alcoholic drinks","bakery products","brewing","dairy products","food and drink manufacturing","free from","allergen free food","frozen and chilled
Thanks Rafa - I have seen it but its slightly different my side. They're still debating the structure so once agreed ill import it the correct way

2023-02-23 11:31 UTC, mforner13 approved these changes
LGTM 👍

2023-02-23 11:31 UTC, stuart-madetech commented on CHANGELOG.md
> +* IOO-402 - International Online Offer triage question 1 allowing user to select business sector
IOO-400 went out with the reskin and 402 ive added to pre-release enhancements

2023-02-23 11:35 UTC, rafa-garcia commented on international_online_offer/templates/ioo/triage/sector.html
> +        { "Food & Drink": ["casual dining","dining","alcoholic drinks","bakery products","brewing","dairy products","food and drink manufacturing","free from","allergen free food","frozen and chilled
It would require a little transformation, though.

To pull it from d-constants:

```
from directory_constants import choices

choices.all_sectors()
```

2023-02-23 11:44 UTC, merged