EAM-104 Webinar buttons
uktrade/great-cms pull request #2046
Opened 2023-03-17 14:54 UTC by timothyPatterson

This PR adds (unstyled) webinar join and view buttons in addition to modifying the existing book and cancel form buttons. Key button attributes are generated programatically and subsequently rendered via an include template. The result of the EventButtonHelper class is an array of button specifications meaning that multiple buttons can be returned.

### Workflow

- [x]  https://uktrade.atlassian.net/jira/software/projects/KLS/boards/359?selectedIssue=KLS-360
- [x] Jira ticket has the correct status.
- [x] [Changelog](CHANGELOG.md) entry added.

### Merging

- [x] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

2023-03-17 15:58 UTC, bsabhilash commented on export_academy/models.py
> +    NOT_STARTED = 'not_started'
Since these are constants, should we define them elsewhere?

2023-03-17 15:58 UTC, bsabhilash commented on export_academy/views.py
> +        return EventButtonHelper().get_buttons_for_obj(user, obj)
If this is only used once, should this be a function than a class method?

2023-03-17 15:58 UTC, bsabhilash commented on export_academy/helpers.py
> +    def get_buttons_for_obj(self, user, obj):
Nice one. Good base for expanding its capability!

2023-03-17 16:14 UTC, timothyPatterson commented on export_academy/models.py
> +    NOT_STARTED = 'not_started'
Conceptually they are quite tightly coupled to an event instance so I thought it made sense to have here as opposed to the reader having to skip to another file to see the value. However, happy to move - where do you think?

2023-03-17 16:16 UTC, timothyPatterson commented on export_academy/views.py
> +        return EventButtonHelper().get_buttons_for_obj(user, obj)
Sure, no probs.

2023-03-17 16:16 UTC, timothyPatterson commented on export_academy/helpers.py
> +    def get_buttons_for_obj(self, user, obj):
Thanks 😄

2023-03-17 16:25 UTC, bsabhilash commented on export_academy/models.py
> +    NOT_STARTED = 'not_started'
Agree. I am not really a fan of putting in far-off places. 2 options I can think of is
1. `from core.constants` import this the theme I can see. Either put it in code or create a EA constant file
2. Place it on top of the file, below imports.
I would say, adding a constant as part of the class is inappropriate, as it is difficult to use for anyone outside the class. but again what if no one wants to use it :)

2023-03-20 08:55 UTC, hal274 commented on export_academy/models.py
> +    NOT_STARTED = 'not_started'
I like the idea of keeping a few constants at top of file. However if it's begins to grow it will make the code difficult to read so at that point extracting to a separate file will be better. 

Generally, separating constants from objects is cleaner regardless of number of re-use

2023-03-20 09:09 UTC, bsabhilash commented on export_academy/models.py
> +    NOT_STARTED = 'not_started'
Ok, As I am voted out, will resolve this conv.

2023-03-20 09:25 UTC, rafa-garcia approved these changes
Nice one, LGTM 👍🏻

2023-03-20 11:32 UTC, timothyPatterson commented on export_academy/views.py
> +        return EventButtonHelper().get_buttons_for_obj(user, obj)
Changed to function.

2023-03-20 11:47 UTC, bsabhilash commented on export_academy/helpers.py
> +            elif event.completed:
When/If the event is marked as completed while EXPORT_ACADEMY_EVENT_IN_PROGRESS, control will not reach here

2023-03-20 11:47 UTC, bsabhilash commented on export_academy/helpers.py
> +            if event.status is EXPORT_ACADEMY_EVENT_NOT_STARTED:
Control will fall through if event is not marked as complete  and time has expired. 
I am suggesting to add another if to check in the end to see event time hs expired and show no buttons (or check with PM to confirm)

2023-03-20 11:55 UTC, timothyPatterson commented on export_academy/helpers.py
> +            elif event.completed:
Good catch, thanks. I have moved the if event.completed to first in control flow.

2023-03-20 11:55 UTC, timothyPatterson commented on export_academy/helpers.py
> +            if event.status is EXPORT_ACADEMY_EVENT_NOT_STARTED:
No buttons is the default result so I think this will be ok.

2023-03-20 11:58 UTC, rafa-garcia requested changes

2023-03-20 11:58 UTC, rafa-garcia commented on core/constants.py
> +EXPORT_ACADEMY_EVENT_NOT_STARTED = 'not_started'
I do not think there is a case for polluting the constants in the core app just to assign values to event objects. This is going against the regular practice of defining constants in the class when only the class will make use of the values.

2023-03-20 13:14 UTC, timothyPatterson commented on export_academy/models.py
> +    EVENT_NOT_STARTED = 'not_started'
No worries @rafa-garcia , I think this is a good comment and have implemented.

2023-03-20 13:34 UTC, rafa-garcia approved these changes

2023-03-20 13:50 UTC, merged