Added microsite nav
uktrade/great-cms pull request #2072
Opened 2023-03-27 15:09 UTC by LuptonM

(https://www.figma.com/file/BeCQ2ET2NKmI5MP1WCbGiP/Microsites?node-id=10-60&t=hmhJk3EOpz1yngHN-0)
_Tick or delete as appropriate:_

### Workflow

- [ ] Ticket exists in Jira https://uktrade.atlassian.net/browse/TICKET_ID_HERE
- [ ] Jira ticket has the correct status.
- [ ] [Changelog](CHANGELOG.md) entry added.

### Reviewing help

- [ ] Explains how to test locally, including how to set up appropriate data
- [ ] Includes screenshot(s) - ideally before and after, but at least after

### Housekeeping

- [ ] Added all new environment variables to Vault.
- [ ] Cleaned up old feature flags
- [ ] Upgraded any vulnerable dependencies.
- [ ] Ran the `make manage download_geolocation_data` command
- [ ] I have updated security dependencies
- [ ] Python requirements have been re-compiled.
- [ ] Frontend assets have been re-compiled.

### Merging

- [x] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

2023-03-27 15:22 UTC, lewis-coulson-dit requested changes

2023-03-27 15:22 UTC, lewis-coulson-dit commented on core/templates/microsites/includes/microsite_nav.html
> +            {% for item in menu_items %}
need a `<ul>` here

2023-03-27 15:22 UTC, lewis-coulson-dit commented on core/templates/microsites/base.html
> +{% comment %}
do you need the comment here

2023-03-27 15:22 UTC, lewis-coulson-dit commented on styles/microsite/nav.scss
> +  background-color: $color-footer;
use a util class like this one for generic styling - https://github.com/uktrade/great-cms/blob/develop/styles/great/_utils.scss#L54

2023-03-27 15:22 UTC, lewis-coulson-dit commented on styles/microsite/nav.scss
> +    padding-top: $standard-padding;
use the govuk util classes for padding/margin where possible i.e `govuk-!-padding-5` or whatever size you need - https://design-system.service.gov.uk/styles/spacing/

2023-03-27 16:55 UTC, LuptonM commented on styles/microsite/nav.scss
> +  background-color: $color-footer;
Not sure about using a util class just to add a background color. If the color changes then instead of changing 1 variable i'd have to swap all the class names out

2023-03-27 17:07 UTC, lewis-coulson-dit commented on styles/microsite/nav.scss
> +  background-color: $color-footer;
Ok if you think thats best. I would strongly recommend using as much GOVUK code as possible to reduce the amount of css you are writing though and to make this more scalable. Where possible add/use generic great specific code in the `styles/great` folder as well again to reduce the amount of css you need to write.

2023-03-29 08:41 UTC, lewis-coulson-dit approved these changes

2023-03-29 08:44 UTC, merged