KLS-1659
uktrade/great-cms pull request #2786
Opened 2023-12-11 11:20 UTC by LuptonM

(Please add a sentence or two explaining the context of this PR. Reviewers can go to the ticket for detail.)
CONTEXT: This changeset adds/removes/updates [summary of feature/area/code] so that [summary of benefit].

_Tick or delete as appropriate:_

### Workflow

- [ ] Ticket exists in Jira https://uktrade.atlassian.net/browse/TICKET_ID_HERE
- [ ] Jira ticket has the correct status.
- [ ] A clear/description pull request messaged added.

### Reviewing help

- [ ] Explains how to test locally, including how to set up appropriate data
- [ ] Includes screenshot(s) - ideally before and after, but at least after

### Housekeeping

- [ ] Added all new environment variables to Vault.
- [ ] Cleaned up old feature flags
- [ ] Upgraded any vulnerable dependencies.
- [ ] Ran the `make manage download_geolocation_data` command
- [ ] I have updated security dependencies
- [ ] Python requirements have been re-compiled.
- [ ] Frontend assets have been re-compiled.
- [ ] I have checked that my PR is using the latest package versions of: great-components, directory-constants, directory-healthcheck, directory-validators, directory-components, directory-api-client, directory-ch-client, django-staff-sso-client, directory-forms-api-client, directory-sso-api-client, sigauth

### Merging

- [x] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

2023-12-12 15:57 UTC, divyaparameswaran commented on core/templatetags/content_tags.py
> +def millify(n):
Any reason we moved this func here instead of the helpers ?

2023-12-13 13:19 UTC, LuptonM commented on core/templatetags/content_tags.py
> +def millify(n):
i had moved it as i put some logic into a page helper and was havign circular issues but dont need it now

2023-12-13 15:52 UTC, divyaparameswaran commented on core/templatetags/content_tags.py
> +# from core.helpers import millify
Don't think we need this line as the import is on line 15 .

2023-12-13 15:53 UTC, divyaparameswaran approved these changes
lgtm

2023-12-14 11:15 UTC, lewis-coulson-dit requested changes
You need to use the card component not just adding the "great-card" class to this

2023-12-19 11:10 UTC, divyaparameswaran approved these changes

2023-12-20 14:32 UTC, hal274 commented on core/templatetags/content_tags.py
> +        html_content = f"""
@LuptonM any plans to address codecov?

2023-12-20 15:06 UTC, hal274 approved these changes

2023-12-20 16:27 UTC, hal274 commented
Merging as the outstanding comment from @lewis-coulson-dit has been addressed and he is off work atm

2023-12-20 16:27 UTC, merged