GP2-420-get-topic-details
uktrade/great-cms pull request #353
Opened 2020-09-08 16:11 UTC by depsiatwal

- [ ] Change has a jira ticket that has the correct status.
 - [ ] Changelog entry added.

2020-09-08 16:45 UTC, bobmeredith requested changes

2020-09-08 16:45 UTC, bobmeredith commented on core/migrations/0032_auto_20200908_1151.py
> +            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.StructBlock([('segment', wagtail.core.blocks.ChoiceBlock(choices=wagtail_personalisation.blocks.list_segment_choic
Just wondering why this streamfield is being altered. AFAICT, you didn't change the model.  Maybe it's migration crossover.

2020-09-08 16:45 UTC, bobmeredith commented on core/wagtail_hooks.py
> +        return page
I think I can see some issues with this.
As you're only looping pages in the topics in this `curated_list_page`, if a page is removed from a topic - or indeed if the lesson page in a topic is changed, the `topic_block_id` won't be cleared.
Also, why the check for `not topic_pages.specific.topic_block_id`? I think you should set the `topic_block_id` even if it's already populated but does not = this `topic.id` (in case a lesson is moved from one topic to another).

You could do this by clearing all lesson pages with this topic_block id `Detail_page.objects.filter(topic_block_id=topic.id)` or - better by making a map of the ids, ticking them off as you find lesson pages in this topic, then wiping the topic_block_id from the remainder.

You're right - it's a tricky thing!

2020-09-09 08:44 UTC, stevejalim commented on core/migrations/0032_auto_20200908_1151.py
> +            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.StructBlock([('segment', wagtail.core.blocks.ChoiceBlock(choices=wagtail_personalisation.blocks.list_segment_choic
Yeah, I agree. As a separate ticket, we could add a small test to the suite to catch a missing migration to avoid it in the future.

2020-09-09 10:18 UTC, bobmeredith approved these changes
Nice one.

2020-09-09 10:19 UTC, merged