Added auto escape for case study section
uktrade/great-cms pull request #479
Opened 2020-10-16 10:12 UTC by webbyfox

- [x] Ticket exists in Jira  https://uktrade.atlassian.net/browse/TICKET_ID_HERE 
 - [x] Jira ticket has the correct status.
 - [x] [Changelog](CHANGELOG.md) entry added.
 - [X] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

2020-10-17 08:52 UTC, bobmeredith requested changes

2020-10-17 08:52 UTC, bobmeredith commented on core/templates/core/case_study_block.html
> +                <h3 class="h-m m-b-xs p-0">{% autoescape off %}{{case_study.summary}}{% endautoescape %}</h3>
This doesn't feel at all right.  
These fields should be text not HTML, so an apostrophe should get encoded as '&apos;' or something and appear correctly.
Encoding is enabled by default because otherwise you are vulnerable to cross-site-scripting.

2020-10-17 08:52 UTC, bobmeredith commented on react-components/src/components/CaseStudy/CaseStudy.jsx
> +      <h3 className="h-m m-b-xs p-0" dangerouslySetInnerHTML={{ __html: heading }} />
Likewise - it's called 'dangerour' for a reason.  There is something wrong here and I don't think this is the solution

2020-10-17 09:22 UTC, bobmeredith commented
I had a look at the code. It looks like the casestudy gets re-rendered by javascript, so the issue is that it's being encoded twice.
The neatest way to fix it is probably similar to the way the body is handled - i.e. in the script block in case_study_block, 
```
company:document.querySelector('#case_study . case-study__company').innerText
```
(If you use innerText, you're getting just text so when React re-renders, it should be html encoded in the normal way.)
If you grab the HTML instead as 'body' is done, it will need the 'dangerouslySetInnerHTML' - but I think it's better to avoid that where possible.

Actually, I think the block of querySelectors would be neater by setting a variable to the case_study ->
```
let caseStudy = document.querySelector('#case_study')
... 
heading: caseStudy.querySelector('h3'.innerText,)
company: caseStudy.querySelector('.case-study__company').innerText,
...
```

2020-10-19 09:41 UTC, webbyfox commented
@bobmeredith would you mind to have a look when you got a moment

2020-10-19 09:54 UTC, bobmeredith requested changes

2020-10-19 09:54 UTC, bobmeredith commented on core/templates/core/case_study_block.html
> +                <p class="case-study__company h-xs p-0">{{case_study.company_name|safe}}</p>
I don't think you should have a safe filter on heading or company. case_study.summary and case_study.company_name are both text, not HTML.

2020-10-19 09:54 UTC, bobmeredith commented on react-components/src/components/CaseStudy/CaseStudy.jsx
> +      <h3 className="h-m m-b-xs p-0" dangerouslySetInnerHTML={{ __html: heading }} />
You're getting innerText, so I think `<h3 className="h-m m-b-xs p-0">{heading}</h3>` is fine. React should escape your apostrophe to `&apos;` at this step.

2020-10-19 09:54 UTC, bobmeredith commented on react-components/src/components/CaseStudy/CaseStudy.jsx
>                <div className="case-study__media body-l" dangerouslySetInnerHTML={{ __html: body }} />
Ditto

2020-10-19 10:14 UTC, bobmeredith approved these changes
LGTM

2020-10-19 10:37 UTC, merged