Feature/gp2 857 site footer
uktrade/great-cms pull request #618
Opened 2020-11-04 14:03 UTC by jakehopking

## To do (delete all that do not apply):

 - [X] Ticket exists in Jira  https://uktrade.atlassian.net/browse/GP2-936
 - [X] Jira ticket has the correct status.
 
 - [X] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

2020-11-04 14:08 UTC, jakehopking commented on core/templates/core/footer.html
> +      <a href="/">
Fixed.

2020-11-05 11:06 UTC, depsiatwal commented on CHANGELOG.md
> +
Can we add a CL entry please

2020-11-05 12:48 UTC, bobmeredith requested changes

2020-11-05 12:48 UTC, bobmeredith commented on core/templates/core/footer.html
> -        <a href="{% url_map 'terms' %}">Terms and conditions</a>
This should not cause a breakage with original code - but the value of the url 'terms' should be populated into constants and put in the lookup map in the url_map template tag.

2020-11-05 12:48 UTC, bobmeredith commented on core/templates/core/footer.html
> -        <a href="{% url_map "privacy" %}">Privacy notice</a>
This should not cause a breakage with original code - but the value of the url 'privacy' should be populated into constants and put in the lookup map in the url_map template tag.

2020-11-05 12:48 UTC, bobmeredith commented on core/templates/core/footer.html
> -      <a href="{% url home %}">
This is a link to the homepage. It's a wagtail page in fact so a reverse lookup won't work.  Suggest you just use '/' as in the header.

2020-11-05 13:25 UTC, stevejalim commented on core/templates/core/footer.html
> -      <a href="{% url home %}">
Yeah, even though django-doctor said not to use "/" I think the advice the bot gave wasn't useful here. "/" is a VERY common (and stable) approach to linking to the homepage

2020-11-05 16:59 UTC, jakehopking commented on CHANGELOG.md
> +
What does this mean?

2020-11-05 16:59 UTC, jakehopking commented on core/templates/core/footer.html
> -      <a href="{% url home %}">
Exactly @stevejalim - I had it set as "/"  before this bot suggested something that caused (indirectly) build errors.

2020-11-05 17:02 UTC, jakehopking commented on core/templates/core/footer.html
> -        <a href="{% url_map "privacy" %}">Privacy notice</a>
Sorry @bobmeredith I don't understand your comment regarding constants here. I was under the impression that @depsiatwal was going to do this kind of work as part of the BE task associated with this.

2020-11-05 17:07 UTC, jakehopking commented on core/templates/core/footer.html
> -        <a href="{% url_map "privacy" %}">Privacy notice</a>
Updated to single quotes.

2020-11-06 10:01 UTC, jakehopking commented on core/templates/core/footer.html
> -        <a href="{% url_map "privacy" %}">Privacy notice</a>
@bobmeredith, as mentioned @depsiatwal has added these as constants already: https://uktrade.atlassian.net/browse/GP2-936

2020-11-06 10:02 UTC, jakehopking commented on core/templates/core/footer.html
> -        <a href="{% url_map 'terms' %}">Terms and conditions</a>
https://uktrade.atlassian.net/browse/GP2-936

2020-11-06 10:14 UTC, depsiatwal approved these changes
LGTM

2020-11-06 10:30 UTC, merged