Gp2 1559 structualmarketing page v3
uktrade/great-cms pull request #980
Opened 2021-02-26 10:10 UTC by Rambowalsh

(Please add a sentence or two explaining the context of this PR. Reviewers can go to the ticket for detail.)
CONTEXT: This changeset adds/removes/updates [summary of feature/area/code] so that [summary of benefit].

_Tick or delete as appropriate:_

### Workflow

- [ ] Ticket exists in Jira https://uktrade.atlassian.net/browse/TICKET_ID_HERE/GP2-1559
- [ ] Jira ticket has the correct status.
- [ ] [Changelog](CHANGELOG.md) entry added.

### Reviewing help

- [ ] Explains how to test locally, including how to set up appropriate data
- [ ] Includes screenshot(s) - ideally before and after, but at least after

### Housekeeping

- [ ] Added all new environment variables to Vault.
- [ ] Cleaned up old feature flags
- [ ] Upgraded any vulnerable dependencies.
- [ ] I have updated security dependencies
- [ ] Python requirements have been re-compiled.
- [ ] Frontend assets have been re-compiled.

### Merging

- [x] This PR can be merged by reviewers. (If unticked, please leave for the author to merge)

2021-02-26 11:06 UTC, bobmeredith reviewed
Good if you could check the boxes, add some context and delete inappropriate in the comment section of PR.  Oh, and fix the jira link.

2021-02-26 11:07 UTC, webbyfox requested changes
Hey @Rambowalsh  Thanks for this PR. Sorry but there are some changes required for this PR. I've added comments. Also, we add changelog entries for every PR so when we release to Beta/Prod we have a list of entries that we can make as a changelog.

2021-02-26 11:07 UTC, webbyfox commented on tests/unit/core/test_models.py
> +    case_study = CaseStudyFactory(company_name='Test Co')
same for this - update your branch with develop and run migration

2021-02-26 11:07 UTC, webbyfox commented on domestic/models.py
> +        return HttpResponseNotFound
I think this need to be an instance rather class

2021-02-26 11:07 UTC, webbyfox commented on domestic/models.py
> +        return HttpResponseNotFound
I think this need to be an instance rather class

2021-02-26 11:07 UTC, webbyfox commented on tests/unit/core/factories.py
> +# Added by CW for ticket GP2-1559
Remove this comment please

2021-02-26 11:07 UTC, webbyfox commented on tests/unit/core/test_models.py
> +# Added by CW for GP2-1559
Remove this comment please

2021-02-26 11:16 UTC, Rambowalsh commented
> Good if you could check the boxes, add some context and delete inappropriate in the comment section of PR. Oh, and fix the jira link.

https://uktrade.atlassian.net/browse/GP2-1559

Won't let me update the link

2021-02-26 11:16 UTC, stevejalim reviewed
hi @Rambowalsh - thanks for this.

There are a few things to tweak - please see the comments and ask if you have any questions.

Am pretty hopeful that addressing the things in the comments related to the unexpected changes will fix up the failing tests in CI.

Also, please add an entry to CHANGELOG.md (see the new-developer notes in Confluence that we shared the other day) 

(We generally add fixups as further commits to the branch, then push them up - no need to amend existing commits here, etc - it's all code evolving ever-forward 😄  )

Cheers!
Steve

2021-02-26 11:16 UTC, stevejalim commented on domestic/models.py
> +        return HttpResponseNotFound
A couple of things to fix here:

1) `return HttpResponseNotFound` doesn't work - if you add a `StructuralPage` in Wagtail and publish it, then view that live page, it will throw a 500 because it's the class that has been returned, not an instance of the class. 

2) Changing it to `return HttpResponseNotFound()` **does** stop things blowing up, but renders an empty page, because returning an instance of `HttpResponseNotFound()` means that instance needs to also define the HTML to be shown

eg `return HttpResponseNotFound('<h1>Page not found</h1>')`

Instead, to get the standard 404 page for Magna, we need to `raise Http404()` instead. 

(If you have DEBUG=True you'll see the yellow debug 404 page. If you se DEBUG=False in your `secrets-do-not-commit` you will get the proper 404 page)

The docs at https://docs.djangoproject.com/en/3.1/topics/http/views/#the-http404-exception cover all this nicely.

2021-02-26 11:16 UTC, stevejalim commented on tests/unit/core/factories.py
> +    summary = factory.fuzzy.FuzzyText(length=200)
Not sure why these were changed, but I suspect they are the reason the test suite is failing. `make pytest` locally to confirm whether changing these back fixes things.

2021-02-26 11:16 UTC, stevejalim commented on tests/unit/core/test_models.py
> +    case_study = CaseStudyFactory(title='', company_name='Test Co')
Similarly here, this is an unrelated test and it I'd guess that some old changes were chosen over newer changes when merging in `develop` or rebasing onto `develop`. Easy to amend back, by examining the diff here - don't worry about trying to re-rebase etc

2021-02-26 11:16 UTC, stevejalim commented on tests/unit/core/test_models.py
> +        assert resp.status_code == HttpResponseNotFound.status_code
This test will need refactoring to show that `Http404` is raised instead. eg

```
    with pytest.raises(HTTPError):
        assert resp.status_code == HttpResponseNotFound.status_code
```

2021-02-26 11:18 UTC, stevejalim commented on .gitignore
> +great-cms/python40
Chris's venv is, for some reason, inside great-cms. I said that for now it's fine to add to gitignore, rather than get bogged down in further setup stuff - hope that's cool @webbyfox

2021-02-26 13:21 UTC, Rambowalsh commented on domestic/models.py
> +# Added by CW for ticket GP2-1559
Removed comments

2021-02-26 15:43 UTC, Rambowalsh commented on domestic/models.py
> +# Added by CW for ticket GP2-1559
Removed

2021-02-26 15:44 UTC, Rambowalsh commented on tests/unit/core/factories.py
> +    summary = factory.fuzzy.FuzzyText(length=200)
Rizwan amended

2021-02-26 15:44 UTC, Rambowalsh commented on tests/unit/core/test_models.py
> +    case_study = CaseStudyFactory(title='', company_name='Test Co')
Rizwan amended

2021-02-26 15:44 UTC, Rambowalsh commented on tests/unit/core/test_models.py
> +    case_study = CaseStudyFactory(company_name='Test Co')
Rizwan amended

2021-02-26 15:45 UTC, Rambowalsh commented on domestic/models.py
> +        return HttpResponseNotFound
mended too  return HttpResponseNotFound()

2021-02-26 15:45 UTC, Rambowalsh commented on tests/unit/core/test_models.py
> +# Added by CW for GP2-1559
Removed comment

2021-02-26 15:48 UTC, Rambowalsh commented on tests/unit/core/factories.py
> +    summary = factory.fuzzy.FuzzyText(length=200)
Rizwan amended, I don't understand how these changed as I never touched them

2021-02-26 15:48 UTC, Rambowalsh commented on tests/unit/core/test_models.py
> +    case_study = CaseStudyFactory(title='', company_name='Test Co')
Again Rizwan amended these, not sure how this happened as I never touched them

2021-02-26 15:54 UTC, Rambowalsh commented on domestic/models.py
> +        return HttpResponseNotFound
Amended

2021-03-01 10:31 UTC, Rambowalsh commented on tests/unit/core/test_models.py
> +    case_study = CaseStudyFactory(title='Alice and Bob export to every continent', company_name='Test Co')
Amended

2021-03-01 10:32 UTC, Rambowalsh commented on domestic/models.py
> +        return HttpResponseNotFound
Amended to use correct object

2021-03-01 10:32 UTC, Rambowalsh commented on tests/unit/core/factories.py
> +# Added by CW for ticket GP2-1559
Removed comment

2021-03-01 10:33 UTC, Rambowalsh commented on tests/unit/core/test_models.py
> +        assert resp.status_code == HttpResponseNotFound.status_code
Amended to use Steve's suggestion

2021-03-01 10:44 UTC, Rambowalsh commented on domestic/models.py
> +
Amended code

2021-03-01 10:53 UTC, stevejalim reviewed
@Rambowalsh  Looking pretty good. Could you also add a new entry at the top of the Enhancements section of CHANGELOG.md, please?

Also, you need to merge in (or rebase on) the latest version of `develop` in order to be able to merge this. When you do that, take care to ensure that migration numbers don't clash if someone else has added an 0022 to domestic as well (but I think that's pretty safe right now). Django/runserver will tell you if there are problems with clashing migrations when you run `make manage migrate`

2021-03-01 14:26 UTC, stevejalim approved these changes
Looks good to me - thanks for the fixups!

2021-03-01 14:32 UTC, webbyfox commented
welldone @Rambowalsh :clap:

2021-03-01 14:34 UTC, webbyfox approved these changes

2021-03-01 14:34 UTC, merged